# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EngineeringAITest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'SwiftyJSON', '~> 4.0'

  # Pods for EngineeringAITest

end
